language: ruby
dist: trusty
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - jruby-9.1.12.0
  - jruby-1.7.27
  - ruby-head
  - jruby-head
  - rbx-3.84
before_install:
  - gem update --system
  - gem install bundler
jdk:
  - oraclejdk8

sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-3.84
