language: ruby
dist: trusty
rvm:
  - 2.2.7
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - ruby-head
  - jruby-1.7.27
  - jruby-head
  - rbx-3.84
before_install:
  - gem update --system
  - gem install bundler
after_success:
  - "bundle exec coveralls push"
jdk:
  - oraclejdk8

sudo: false

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 1.9.3
